name: Conformance Tests

on:
  schedule:
    # Every Monday at 6:00 AM UTC
    - cron: "0 6 * * 1"
  workflow_dispatch:
    inputs:
      starter:
        description: "Run a single starter (e.g. node-transcription). Leave empty for all."
        required: false
        type: string

concurrency:
  group: conformance-tests
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        include:
          # transcription (6)
          - { name: node-transcription, use_case: transcription }
          - { name: flask-transcription, use_case: transcription }
          - { name: django-transcription, use_case: transcription }
          - { name: fastapi-transcription, use_case: transcription }
          - { name: deno-transcription, use_case: transcription }
          - { name: csharp-transcription, use_case: transcription }
          # live-transcription (6)
          - { name: node-live-transcription, use_case: live-transcription }
          - { name: flask-live-transcription, use_case: live-transcription }
          - { name: django-live-transcription, use_case: live-transcription }
          - { name: fastapi-live-transcription, use_case: live-transcription }
          - { name: deno-live-transcription, use_case: live-transcription }
          - { name: csharp-live-transcription, use_case: live-transcription }
          # text-to-speech (5)
          - { name: node-text-to-speech, use_case: text-to-speech }
          - { name: flask-text-to-speech, use_case: text-to-speech }
          - { name: django-text-to-speech, use_case: text-to-speech }
          - { name: fastapi-text-to-speech, use_case: text-to-speech }
          - { name: deno-text-to-speech, use_case: text-to-speech }
          # live-text-to-speech (6)
          - { name: node-live-text-to-speech, use_case: live-text-to-speech }
          - { name: flask-live-text-to-speech, use_case: live-text-to-speech }
          - { name: django-live-text-to-speech, use_case: live-text-to-speech }
          - { name: fastapi-live-text-to-speech, use_case: live-text-to-speech }
          - { name: deno-live-text-to-speech, use_case: live-text-to-speech }
          - { name: csharp-live-text-to-speech, use_case: live-text-to-speech }
          # text-intelligence (5)
          - { name: node-text-intelligence, use_case: text-intelligence }
          - { name: flask-text-intelligence, use_case: text-intelligence }
          - { name: django-text-intelligence, use_case: text-intelligence }
          - { name: fastapi-text-intelligence, use_case: text-intelligence }
          - { name: deno-text-intelligence, use_case: text-intelligence }
          # voice-agent (6)
          - { name: node-voice-agent, use_case: voice-agent }
          - { name: flask-voice-agent, use_case: voice-agent }
          - { name: django-voice-agent, use_case: voice-agent }
          - { name: fastapi-voice-agent, use_case: voice-agent }
          - { name: deno-voice-agent, use_case: voice-agent }
          - { name: csharp-voice-agent, use_case: voice-agent }

    # Skip matrix entries that don't match the filter (when set)
    if: ${{ !inputs.starter || inputs.starter == matrix.name }}

    env:
      PREVIEW_BASE: https://preview.dx.deepgram.com
      FLY_APP: deepgram-${{ matrix.name }}

    steps:
      # Checkout the monorepo (shallow, no submodule content) for deepgram.toml files.
      # Submodules use SSH URLs which need extra auth setup, so we init without cloning
      # and only fetch the specific starter's deepgram.toml via its individual repo.
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Fetch the starter's deepgram.toml from its individual GitHub repo.
      # The metadata tests need REPO_PATH to point at a directory containing deepgram.toml.
      - name: Fetch starter deepgram.toml
        run: |
          mkdir -p "${{ matrix.name }}"
          curl -sf "https://raw.githubusercontent.com/deepgram-starters/${{ matrix.name }}/main/deepgram.toml" \
            -o "${{ matrix.name }}/deepgram.toml"

      # Checkout starter-contracts as a sibling directory (avoid nested submodule SSH issues).
      # Requires GH_PAT secret with repo scope for cross-org access (deepgram/starter-contracts).
      - name: Checkout starter-contracts
        uses: actions/checkout@v4
        with:
          repository: deepgram/starter-contracts
          path: starter-contracts
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install test dependencies
        working-directory: starter-contracts
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: starter-contracts
        run: npx playwright install chromium

      - name: Wake up Fly machine
        run: |
          echo "Waking up ${{ env.FLY_APP }}..."
          curl -sf "${{ env.PREVIEW_BASE }}/${{ matrix.name }}/" > /dev/null || true

          # Poll /api/metadata until backend responds (up to 60s)
          for i in $(seq 1 12); do
            if curl -sf "${{ env.PREVIEW_BASE }}/${{ matrix.name }}/api/metadata" > /dev/null 2>&1; then
              echo "Backend is ready (attempt $i)"
              exit 0
            fi
            echo "Waiting for backend... (attempt $i/12)"
            sleep 5
          done

          echo "::error::Backend did not respond within 60 seconds"
          exit 1

      - name: Run API tests (vitest)
        working-directory: starter-contracts
        env:
          BASE_URL: ${{ env.PREVIEW_BASE }}/${{ matrix.name }}
          WS_URL: wss://preview.dx.deepgram.com/${{ matrix.name }}
          REPO_PATH: ${{ github.workspace }}/${{ matrix.name }}
          SESSION_AUTH: "true"
        run: |
          npx vitest run \
            "interfaces/${{ matrix.use_case }}/conformance/" \
            "tests/${{ matrix.use_case }}/api/" \
            --exclude "**/session.spec.js" \
            --exclude "**/session.test.js"

      - name: Run UI tests (playwright)
        working-directory: starter-contracts
        env:
          BASE_URL: ${{ env.PREVIEW_BASE }}/${{ matrix.name }}
          CI: "true"
        run: |
          npx playwright test \
            "tests/${{ matrix.use_case }}/ui/workflow.spec.js"

      - name: Collect Fly logs on failure
        if: failure()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          mkdir -p /tmp/fly-logs
          if command -v fly &> /dev/null; then
            fly logs -a "${{ env.FLY_APP }}" --no-tail -n 200 \
              > /tmp/fly-logs/${{ matrix.name }}.log 2>&1 || true
          else
            curl -L https://fly.io/install.sh | sh 2>/dev/null
            ~/.fly/bin/fly logs -a "${{ env.FLY_APP }}" --no-tail -n 200 \
              > /tmp/fly-logs/${{ matrix.name }}.log 2>&1 || true
          fi

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-${{ matrix.name }}
          retention-days: 7
          path: |
            starter-contracts/test-results/
            /tmp/fly-logs/
